const express = require('express');
const bodyParser = require('body-parser');
const PORT = process.env.PORT;
const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.listen(3000, () => console.log('Webhook server is listening, port 3000'));
const verificationController=require('./controllers/verification.js');
const messageWebhookController = require('./Helpers/messageWebhook.js');
app.get('/', verificationController);
app.post('/', messageWebhookController);
